version: '3.3'
services:
  microservices-account-service-postgres-dev:
    container_name: account-service-postgres-dev
    image: postgres:12.1
    restart: always
    env_file: .env.development
    environment:
      POSTGRES_USER: ${MIC_ACCOUNT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MIC_ACCOUNT_POSTGRES_PASSWORD}
      POSTGRES_DB: ${MIC_ACCOUNT_POSTGRES_DATABASE}
    volumes:
      - 'account-service-postgres-dev:/var/lib/postgresql/data'
    ports:
      - ${MIC_ACCOUNT_POSTGRES_EXTERNAL_PORT}:${MIC_ACCOUNT_POSTGRES_PORT}

volumes:
  account-service-postgres-dev:
